name: Build and Test
on:
  push:
    branches: [ 'master' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: csaude/openmrs-module-debezium
          path: openmrs-module-debezium
      - uses: actions/checkout@v4
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Build and test with maven
        run: mvn test
      - name: Install debezium module
        working-directory: openmrs-module-debezium
        run: mvn install
